export enum ContentTypeEnum {
    NO_DOTS = "NO_DOTS",
    DOTS = "DOTS",
    IMAGE_DISPLAY_ALL_01 = "IMAGE_DISPLAY_ALL_01",
    IMAGE_DISPLAY_ALL_02 = "IMAGE_DISPLAY_ALL_02",
    CAROUSEL = "CAROUSEL",
    COMPOSIT_CONTENT = "COMPOSIT_CONTENT"
}