export enum ContentTypeEnum {
    NO_DOTS = "NO_DOTS",
    DOTS = "DOTS",
    IMAGE_DISPLAY_ALL_01 = "IMAGE_DISPLAY_ALL_01",
    IMAGE_DISPLAY_ALL_02 = "IMAGE_DISPLAY_ALL_02",
    CAROUSEL = "CAROUSEL",
    COMPOSIT_CONTENT = "COMPOSIT_CONTENT",
    SHOW_CASE_01 = "SHOW_CASE_01",
    SHOW_CASE_02 = "SHOW_CASE_02",
    UPPER_RIGHT_CARD = "UPPER_RIGHT_CARD",
    LOWER_LEFT_TITLE = "LOWER_LEFT_TITLE"
}